spring:
  application.name: consumer-service
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP:localhost:9092}
    consumer:
      group-id: claim-check-demo
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      properties:
        max.partition.fetch.bytes: 3145728
        partition.assignment.strategy: org.apache.kafka.clients.consumer.CooperativeStickyAssignor
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      acks: all
      properties:
        max.request.size: 3145728
  data:
    mongodb:
      uri: ${MONGO_URI:mongodb://localhost:27017/claimcheck?w=majority}
server.port: 8091
app:
  chain.length: ${CHAIN_LENGTH:20}
management:
  endpoints.web.exposure.include: health,prometheus,metrics
  metrics.distribution.percentiles-histogram:
    consumer.processing: true
    consumer.mongo.fetch: true